#cloud-config
runcmd:
  - apt-get update
  - apt install -y openjdk-8-jre-headless
  - wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-4.0.tgz
  - tar xvfz apache-jmeter-4.0.tgz
  - ln -s /apache-jmeter-4.0 /apache-jmeter
  - echo "export PATH=$PATH:/apache-jmeter/bin" >> /root/.bashrc
