#cloud-config
runcmd:
  - apt-get update
  - apt install -y openjdk-8-jre-headless
  - wget http://mirror.cc.columbia.edu/pub/software/apache/jmeter/binaries/apache-jmeter-4.0.tgz
  - tar xvfz apache-jmeter-4.0.tgz
  - echo "export PATH=$PATH:/apache-jmeter-4.0/bin" >> /root/.bashrc
